trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: yarn
    displayName: "Install packages"

  - script: yarn lint
    displayName: "Lint"

  - script: yarn typecheck
    displayName: "Typecheck"

  - script: yarn test
    displayName: "Run tests"
