trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: yarn
    displayName: "Install packages"

  - script: yarn lint
    displayName: "Lint"

  - script: yarn typecheck
    displayName: "Typecheck"

  - script: yarn test
    displayName: "Run tests"

  - script: yarn build
    displayName: "Build bundle"

  - script: ./pack.sh
    displayName: Pack extension as ZIP

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: /tmp/tabliner.zip
      artifactName: tabliner.zip
